sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t jasenpan1987/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jasenpan1987/react-test npm test
after_success:
  - "./build.sh"
env:
  matrix:
    - secure: kEni7iinR4gGK6pV5SHmdziswasOVDw87LDI0BiKxV+eYHLMY+EwPZ5f61vJQTW3F/v1qzHpmgBeBINf0aHQjfp+DbGJhxKraM6hvsdcu9Wajo3BQk82u+wBcynY21PjdBITK0o0C3QKbYav4L8F1LiHnb+8h5eetRY2hN4EDP96sdxQT4BVDIBBtnvJe5+qQ/V+02zy1ORt3f1TFGbNegRH77j/V67Ya9M7Le78jib3ZkxQvnqtN/nEm6ee9s+SltNBpx8ogRXd2H6WCNM8c4A7RJOv0g2w1ASMryG3x1KeOtmsbQmWeyhVCV1jU29vgbzYbBCn7KlADzHdkF1YdfYNXHF26vUBYQPBXZGFe9FnrVdpuQhigv0QeWZcVA8iEXwtNO5KP3FCGsD/ajtmBG9Py+TB+UftkP1czvE/8IlxnpFlV30xkgY8hE9AF5c5HRX+0J33Z6t9Xf/ZwF9g6tTQtZXkVq3rm14Zp69JGi9bsZsv5osYfkKM8YNyYj5H/un/iNBlFCG6o8ILziCF8FVzVMrios6EH8WVDo/zg38S7Iq7obWz+I6TBuLq2oHnbC/hShV0HFdwhcclXl6QZWYfEFqybBNpQIaEpfC+0f6hPUj1/ymj3UhN60DIVXIuoR1IexiH7S1WJiTOTA/0AHffR3X9tvC+6lkiGm1jvto=
    - secure: Ci7jrK3/5TFZKBkwHlIfj+H3s52LcKMcilxiFS12f0TgD450xn0nggva7/dnS9fbk1mIyPOAeD6kf5AyXim5IeRgsrnjNzdrHEqXVXlk9zrdEEmabC6aohRE6m6KJstoxA9fsVG52xfBvc0e43432MjQ3Hf56kr4E+r9mP2klLNnBzAS/BHpXCfkqS7EIEVhkJtXgsugpZgebuCRb4aGX053pXc5JYFncGMhhCb7CYaM7IRRgV9CHvjiKUOuWfMsbhFk5zZH6I5zO38jdFniEqUHVedM11cCF2oZgNdOiB/MK8BDsJDp3yIdZG6lRyS48G4Q8U5HIjocPXc3b7pO5IuGGr8tzwJQ6PI4ewyO9/diItzOY3UkxhSNIn8+sVbhluwSHj/LdtClp2iwvG/6xMlAtL27rGmzUQBAaVyCidnJ85FPgsguZqB5QT14McT6AvLrVeY9/mlpdkiYZYi7TBuXVMWyAMzjBHas4b3RqUKUjFjxoIW8g4T1yxaqs/JMOdA8q9Y+S/lngSlUsi1TB0nbJ+bFP5bD19T/SGLF8LJ1qtUMNmd5beTp570FONwp2ZG+Nlwh6KnsIAnmNz1JsUhvLYeoZ8UJYC601lNkYUpaUdgs2/npeNcyb69UwY1s2gSbai2jhV8DIWDtp6Z4ogtXm2hK95YQEnRd3MkTEEo=
